# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on: 
      - db

  backend: 
    build: ./backend
    environment: 
      - DB_SERVICE_NAME
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports: 
      - "8000:80"
    depends_on: 
      - db

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local

  